declare const OK: SuccessCode.OK;

declare const ERR_NOT_OWNER: ErrorCode.NOT_OWNER;
declare const ERR_NO_PATH: ErrorCode.NO_PATH;
declare const ERR_NAME_EXISTS: ErrorCode.NAME_EXISTS;
declare const ERR_BUSY: ErrorCode.BUSY;
declare const ERR_NOT_FOUND: ErrorCode.NOT_FOUND;
declare const ERR_NOT_ENOUGH_RESOURCES: ErrorCode.NOT_ENOUGH_RESOURCES;
declare const ERR_NOT_ENOUGH_ENERGY: ErrorCode.NOT_ENOUGH_ENERGY;
declare const ERR_INVALID_TARGET: ErrorCode.INVALID_TARGET;
declare const ERR_FULL: ErrorCode.FULL;
declare const ERR_NOT_IN_RANGE: ErrorCode.NOT_IN_RANGE;
declare const ERR_INVALID_ARGS: ErrorCode.INVALID_ARGS;
declare const ERR_TIRED: ErrorCode.TIRED;
declare const ERR_NO_BODYPART: ErrorCode.NO_BODYPART;
declare const ERR_NOT_ENOUGH_EXTENSIONS: ErrorCode.NOT_ENOUGH_EXTENSIONS;
declare const ERR_RCL_NOT_ENOUGH: ErrorCode.RCL_NOT_ENOUGH;
declare const ERR_GCL_NOT_ENOUGH: ErrorCode.GCL_NOT_ENOUGH;

declare const FIND_EXIT_TOP: FindQuery.EXIT_TOP;
declare const FIND_EXIT_RIGHT: FindQuery.EXIT_RIGHT;
declare const FIND_EXIT_BOTTOM: FindQuery.EXIT_BOTTOM;
declare const FIND_EXIT_LEFT: FindQuery.EXIT_LEFT;
declare const FIND_EXIT: FindQuery.EXIT;
declare const FIND_CREEPS: FindQuery.CREEPS;
declare const FIND_MY_CREEPS: FindQuery.MY_CREEPS;
declare const FIND_HOSTILE_CREEPS: FindQuery.HOSTILE_CREEPS;
declare const FIND_SOURCES_ACTIVE: FindQuery.SOURCES_ACTIVE;
declare const FIND_SOURCES: FindQuery.SOURCES;
declare const FIND_DROPPED_RESOURCES: FindQuery.DROPPED_RESOURCES;
declare const FIND_DROPPED_ENERGY: FindQuery.DROPPED_ENERGY;
declare const FIND_STRUCTURES: FindQuery.STRUCTURES;
declare const FIND_MY_STRUCTURES: FindQuery.MY_STRUCTURES;
declare const FIND_HOSTILE_STRUCTURES: FindQuery.HOSTILE_STRUCTURES;
declare const FIND_FLAGS: FindQuery.FLAGS;
declare const FIND_CONSTRUCTION_SITES: FindQuery.CONSTRUCTION_SITES;
declare const FIND_MY_SPAWNS: FindQuery.MY_SPAWNS;
declare const FIND_HOSTILE_SPAWNS: FindQuery.HOSTILE_SPAWNS;
declare const FIND_MY_CONSTRUCTION_SITES: FindQuery.MY_CONSTRUCTION_SITES;
declare const FIND_HOSTILE_CONSTRUCTION_SITES: FindQuery.HOSTILE_CONSTRUCTION_SITES;
declare const FIND_MINERALS: FindQuery.MINERALS;
declare const FIND_NUKES: FindQuery.NUKES;

declare const TOP: Direction.TOP;
declare const TOP_RIGHT: Direction.TOP_RIGHT;
declare const RIGHT: Direction.RIGHT;
declare const BOTTOM_RIGHT: Direction.BOTTOM_RIGHT;
declare const BOTTOM: Direction.BOTTOM;
declare const BOTTOM_LEFT: Direction.BOTTOM_LEFT;
declare const LEFT: Direction.LEFT;
declare const TOP_LEFT: Direction.TOP_LEFT;

declare const COLOR_RED: ColorCode.RED;
declare const COLOR_PURPLE: ColorCode.PURPLE;
declare const COLOR_BLUE: ColorCode.BLUE;
declare const COLOR_CYAN: ColorCode.CYAN;
declare const COLOR_GREEN: ColorCode.GREEN;
declare const COLOR_YELLOW: ColorCode.YELLOW;
declare const COLOR_ORANGE: ColorCode.ORANGE;
declare const COLOR_BROWN: ColorCode.BROWN;
declare const COLOR_GREY: ColorCode.GREY;
declare const COLOR_WHITE: ColorCode.WHITE;

declare const MOVE: BodyPartType.MOVE;
declare const WORK: BodyPartType.WORK;
declare const CARRY: BodyPartType.CARRY;
declare const ATTACK: BodyPartType.ATTACK;
declare const RANGED_ATTACK: BodyPartType.RANGED_ATTACK;
declare const TOUGH: BodyPartType.TOUGH;
declare const HEAL: BodyPartType.HEAL;
declare const CLAIM: BodyPartType.CLAIM;

declare const STRUCTURE_EXTENSION: StructureType.EXTENSION;
declare const STRUCTURE_RAMPART: StructureType.RAMPART;
declare const STRUCTURE_ROAD: StructureType.ROAD;
declare const STRUCTURE_SPAWN: StructureType.SPAWN;
declare const STRUCTURE_LINK: StructureType.LINK;
declare const STRUCTURE_WALL: StructureType.WALL;
declare const STRUCTURE_KEEPER_LAIR: StructureType.KEEPER_LAIR;
declare const STRUCTURE_CONTROLLER: StructureType.CONTROLLER;
declare const STRUCTURE_STORAGE: StructureType.STORAGE;
declare const STRUCTURE_TOWER: StructureType.TOWER;
declare const STRUCTURE_OBSERVER: StructureType.OBSERVER;
declare const STRUCTURE_POWER_BANK: StructureType.POWER_BANK;
declare const STRUCTURE_POWER_SPAWN: StructureType.POWER_SPAWN;
declare const STRUCTURE_EXTRACTOR: StructureType.EXTRACTOR;
declare const STRUCTURE_LAB: StructureType.LAB;
declare const STRUCTURE_TERMINAL: StructureType.TERMINAL;
declare const STRUCTURE_CONTAINER: StructureType.CONTAINER;
declare const STRUCTURE_NUKER: StructureType.NUKER;
declare const STRUCTURE_PORTAL: StructureType.PORTAL;

declare const RESOURCE_ENERGY: ResourceType.ENERGY;
declare const RESOURCE_POWER: ResourceType.POWER;
declare const RESOURCE_UTRIUM: ResourceType.UTRIUM;
declare const RESOURCE_LEMERGIUM: ResourceType.LEMERGIUM;
declare const RESOURCE_KEANIUM: ResourceType.KEANIUM;
declare const RESOURCE_GHODIUM: ResourceType.GHODIUM;
declare const RESOURCE_ZYNTHIUM: ResourceType.ZYNTHIUM;
declare const RESOURCE_OXYGEN: ResourceType.OXYGEN;
declare const RESOURCE_HYDROGEN: ResourceType.HYDROGEN;
declare const RESOURCE_CATALYST: ResourceType.CATALYST;
declare const RESOURCE_HYDROXIDE: ResourceType.HYDROXIDE;
declare const RESOURCE_ZYNTHIUM_KEANITE: ResourceType.ZYNTHIUM_KEANITE;
declare const RESOURCE_UTRIUM_LEMERGITE: ResourceType.UTRIUM_LEMERGITE;
declare const RESOURCE_UTRIUM_HYDRIDE: ResourceType.UTRIUM_HYDRIDE;
declare const RESOURCE_UTRIUM_OXIDE: ResourceType.UTRIUM_OXIDE;
declare const RESOURCE_KEANIUM_HYDRIDE: ResourceType.KEANIUM_HYDRIDE;
declare const RESOURCE_KEANIUM_OXIDE: ResourceType.KEANIUM_OXIDE;
declare const RESOURCE_LEMERGIUM_HYDRIDE: ResourceType.LEMERGIUM_HYDRIDE;
declare const RESOURCE_LEMERGIUM_OXIDE: ResourceType.LEMERGIUM_OXIDE;
declare const RESOURCE_ZYNTHIUM_HYDRIDE: ResourceType.ZYNTHIUM_HYDRIDE;
declare const RESOURCE_ZYNTHIUM_OXIDE: ResourceType.ZYNTHIUM_OXIDE;
declare const RESOURCE_GHODIUM_HYDRIDE: ResourceType.GHODIUM_HYDRIDE;
declare const RESOURCE_GHODIUM_OXIDE: ResourceType.GHODIUM_OXIDE;
declare const RESOURCE_UTRIUM_ACID: ResourceType.UTRIUM_ACID;
declare const RESOURCE_UTRIUM_ALKALIDE: ResourceType.UTRIUM_ALKALIDE;
declare const RESOURCE_KEANIUM_ACID: ResourceType.KEANIUM_ACID;
declare const RESOURCE_KEANIUM_ALKALIDE: ResourceType.KEANIUM_ALKALIDE;
declare const RESOURCE_LEMERGIUM_ACID: ResourceType.LEMERGIUM_ACID;
declare const RESOURCE_LEMERGIUM_ALKALIDE: ResourceType.LEMERGIUM_ALKALIDE;
declare const RESOURCE_ZYNTHIUM_ACID: ResourceType.ZYNTHIUM_ACID;
declare const RESOURCE_ZYNTHIUM_ALKALIDE: ResourceType.ZYNTHIUM_ALKALIDE;
declare const RESOURCE_GHODIUM_ACID: ResourceType.GHODIUM_ACID;
declare const RESOURCE_GHODIUM_ALKALIDE: ResourceType.GHODIUM_ALKALIDE;
declare const RESOURCE_CATALYZED_UTRIUM_ACID: ResourceType.CATALYZED_UTRIUM_ACID;
declare const RESOURCE_CATALYZED_UTRIUM_ALKALIDE: ResourceType.CATALYZED_UTRIUM_ALKALIDE;
declare const RESOURCE_CATALYZED_KEANIUM_ACID: ResourceType.CATALYZED_KEANIUM_ACID;
declare const RESOURCE_CATALYZED_KEANIUM_ALKALIDE: ResourceType.CATALYZED_KEANIUM_ALKALIDE;
declare const RESOURCE_CATALYZED_LEMERGIUM_ACID: ResourceType.CATALYZED_LEMERGIUM_ACID;
declare const RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE: ResourceType.CATALYZED_LEMERGIUM_ALKALIDE;
declare const RESOURCE_CATALYZED_ZYNTHIUM_ACID: ResourceType.CATALYZED_ZYNTHIUM_ACID;
declare const RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE: ResourceType.CATALYZED_ZYNTHIUM_ALKALIDE;
declare const RESOURCE_CATALYZED_GHODIUM_ACID: ResourceType.CATALYZED_GHODIUM_ACID;
declare const RESOURCE_CATALYZED_GHODIUM_ALKALIDE: ResourceType.CATALYZED_GHODIUM_ALKALIDE;

declare const LOOK_CREEPS:LookQuery.CREEPS;
declare const LOOK_ENERGY:LookQuery.ENERGY;
declare const LOOK_RESOURCES:LookQuery.RESOURCES;
declare const LOOK_SOURCES:LookQuery.SOURCES;
declare const LOOK_MINERALS:LookQuery.MINERALS;
declare const LOOK_STRUCTURES:LookQuery.STRUCTURES;
declare const LOOK_FLAGS: LookQuery.FLAGS;
declare const LOOK_CONSTRUCTION_SITES:LookQuery.CONSTRUCTION_SITES;
declare const LOOK_NUKES: LookQuery.NUKES;
declare const LOOK_TERRAIN:LookQuery.TERRAIN;

declare const ORDER_SELL: OrderType.SELL;
declare const ORDER_BUY: OrderType.BUY;
